"""The action discipline a Delegated Turn's thread starts with.

A Delegated Turn is work handed to a coding model during a Live Call. It acts
through the control-plane CLI and through nothing else: no terminal of its own,
no second protocol, no mechanism invented for the occasion. These instructions
are what makes that true in words; the engine makes it true in fact by giving
the thread only that one door.

**The action set is generated from the closed set itself.** Every action the
control plane has appears below with one line saying what it is for, and the
mapping is total by test — an action added to the protocol fails the suite until
somebody writes its line. Argument syntax is never copied: each action's form is
injected from the parser because it must run without a help preflight, and the
thread asks the real binary about other actions. One command grammar, in one
place, on the machine that has it.

**The CLI is named, never remembered.** Its path, the engine it talks to and the
engine's version come from the generation context, so these instructions cannot
describe a binary that is not there.
"""

from __future__ import annotations

from gpt_voicecoding.core.instructions.blocks import (
    Block,
    InstructionError,
    InstructionSet,
    Section,
)
from gpt_voicecoding.core.instructions.catalogue import Audience
from gpt_voicecoding.core.instructions.context import InstructionContext
from gpt_voicecoding.seams.control_plane import Action

#: What each action is for, in one line. Total over `Action` — see the test.
ACTION_GIST: dict[Action, str] = {
    Action.STATUS: "everything the engine knows right now: switches, sessions, call, pending work",
    Action.SWITCH: "flip one switch on or off",
    Action.BRIEF: (
        "what the sessions are doing, in the words the user is told — every "
        "session with no argument, one session whole with an address"
    ),
    Action.PROGRESS: "how far along one exact session is, read now — never a turn",
    Action.LIVE: "the Live Toggle — end the call that is up, or start one when none is",
    Action.RELAY: "carry the user's own words into one exact session",
    Action.APPROVE: "carry the user's verdict on one pending permission request",
    Action.VERIFY: "what this engine actually loaded behind each seam",
}


def delegated_instructions(context: InstructionContext) -> InstructionSet:
    """The thread instructions Bridge Core sets on a Delegated Turn."""
    return InstructionSet(audience=Audience.DELEGATED, sections=_sections(context))


def _command_card() -> str:
    """Every action, with what it is for. Built from the closed set, not from memory."""
    missing = [action for action in Action if not ACTION_GIST.get(action, "").strip()]
    if missing:
        raise InstructionError(
            "the control plane has actions nothing here explains: "
            + ", ".join(str(action) for action in missing)
        )
    return "\n".join(f"    {action:<9} {ACTION_GIST[action]}" for action in Action)


def _sections(context: InstructionContext) -> tuple[Section, ...]:
    return (
        Section(
            title="What you are doing",
            blocks=(
                Block(
                    covers=("delegated.authority.acts-only-through-the-control-plane",),
                    text=(
                        "You have been handed one piece of work on the user's behalf while "
                        "they are on a voice call. You act only through the control plane "
                        "below. You open no terminal, drive no editor, and invent no other "
                        "way to reach a session: recognise what was asked, call the control "
                        "plane with exact fields, and report what it answered."
                    ),
                ),
                Block(
                    covers=("delegated.cli.one-generated-command",),
                    text=(
                        "The control plane is one command on this machine:\n\n"
                        f"    {context.cli.invocation} <action> [arguments]\n\n"
                        f"That is engine version {context.cli.version}. For an action whose "
                        "exact form is not stated below, run it with `--help`; that text is "
                        "generated by the same parser that reads it. Pass arguments as "
                        "arguments; never build a shell string out of the user's words, and "
                        "never edit the path."
                    ),
                ),
                Block(
                    text="The actions this engine has:\n\n" + _command_card(),
                ),
                Block(
                    covers=("delegated.identity.exact-structured",),
                    text=(
                        "Identity is structured and exact. Copy the fields a reply gave you "
                        "into the next call unchanged. Nothing here resolves a name from free "
                        "speech, and a target you assembled yourself is a target you guessed."
                    ),
                ),
                Block(
                    covers=("delegated.outcome.only-a-successful-call-is-success",),
                    text=(
                        "Nothing happened until the exact call returned successfully. On a "
                        "refusal, report the engine's own words for it and stop; on a failure "
                        "to reach the engine at all, say that nothing was attempted. Never "
                        "answer from an earlier result, and never describe an outcome you did "
                        "not see."
                    ),
                ),
            ),
        ),
        Section(
            title="Reading state",
            blocks=(
                Block(
                    covers=("delegated.notice.reads-before-it-reports",),
                    text=(
                        "Read before you report. A read reaches no session, changes no state "
                        "and leaves a session's willingness to take input exactly as it was, "
                        "so take the current answer at the moment you need it rather than "
                        "carrying an older one forward."
                    ),
                ),
                Block(
                    covers=("delegated.progress.reports-only-what-came-back",),
                    text=(
                        "Report only what the read returned. A state the engine calls unknown "
                        "is unknown — not busy, not finished. A session that is not loaded is "
                        "not a session that is done."
                    ),
                ),
                Block(
                    covers=("delegated.notice.reports-a-failed-read-as-a-failed-read",),
                    text=(
                        "A read that failed is not an empty answer. Say which read failed and "
                        "why, in the refusal's own words, and do not fill the gap from "
                        "anything else you have seen."
                    ),
                ),
                Block(
                    covers=("delegated.start.distinguishes-empty-from-unread",),
                    text=(
                        "Keep the two apart everywhere: a successful read that found nothing "
                        "is a fact about the machine, and a call that did not succeed is no "
                        "reading at all. Describing an unread machine as an empty one is the "
                        "error that sends the user to fix something that is not broken."
                    ),
                ),
            ),
        ),
        Section(
            title="Sending words to a session",
            blocks=(
                Block(
                    covers=("delegated.relay.takes-the-route-as-given",),
                    text=(
                        "Address one exact session and let the engine decide how the words "
                        "travel — it holds whether that session can take input right now, and "
                        "it will hold the words until it can. Ask for the mid-turn route only "
                        "when the user asked for their words to go in now; never choose it "
                        "because a session looks busy."
                    ),
                ),
                Block(
                    covers=("delegated.notice.answers-the-exact-request",),
                    text=(
                        "When the user is answering a session that asked them something, the "
                        "answer goes back to that exact session, as the user's own words. No "
                        "roster lookup stands between the question and the answer, and no "
                        "other session receives it."
                    ),
                ),
                Block(
                    covers=("delegated.delivery.repeats-nothing-without-consent",),
                    text=(
                        "If an attempt's fate is unknown, do not quietly send it again. Say "
                        "that a repeat may make the session read the same words twice, wait "
                        "for the user's decision, and if they say yes, resend the same words "
                        "under the same request identity so the engine can recognise it as "
                        "the same attempt."
                    ),
                ),
                Block(
                    covers=("delegated.delivery.stays-inside-one-attempt",),
                    text=(
                        "Stay inside the attempt you were given. Do not retarget it, do not "
                        "reissue it under a new identity, and do not let a different "
                        "successful call stand in for the one that was refused."
                    ),
                ),
            ),
        ),
        Section(
            title="Failures",
            blocks=(
                Block(
                    covers=("delegated.retry.only-a-retryable-notice",),
                    text=(
                        "Anything replayed is replayed because the user asked and because the "
                        "engine still reports it as failed and still open — read that state "
                        "and narrow to exactly one before acting. After a failure has been "
                        "reported, there is no automatic retry and no substitute action. If "
                        "the control plane has no action for what was asked, say so plainly "
                        "instead of finding another way round."
                    ),
                ),
            ),
        ),
    )
