"""How far along a Claude Session is, read out of the records it wrote.

The cases are **re-expressed** from what the reference implementation proved
about the same read (`legacy@1d32845:bridge/transcript.py:1184-1246,1568-1607,
2828-2860`), not copied: legacy asserted on a JSON-RPC progress reply built by a
daemon with a store behind it, and this asserts on the one value the pure module
returns.

Records here are the shape Claude Code really writes — `isSidechain`, `userType`,
`promptSource`, the nested `message.role` and the ISO-8601 `timestamp` included —
because the exclusions under test *are* those fields, and a fixture that omitted
them would test a reader that never sees a real transcript.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from fakes import PROGRESS_CAPTURE, capture_for
from gpt_voicecoding.adapters.agent.claude.stop_analysis import QUESTION_TOOL
from gpt_voicecoding.adapters.agent.claude.transcript_tail import recent
from gpt_voicecoding.seams.agent import ProgressOmission, ProgressRole

# --- the shapes Claude Code writes -------------------------------------------

#: Every fixture stamps from here, so "newest wins" is a fact about order rather
#: than about whichever clock ran the test.
FIRST = datetime(2026, 8, 26, 4, 30, 0, tzinfo=UTC)


def stamp(seconds: int) -> str:
    """One record's `timestamp`, in the spelling Claude Code writes it."""
    moment = FIRST.replace(second=FIRST.second + seconds)
    return moment.isoformat().replace("+00:00", "Z")


def said(text: str, *, role: str = "assistant", at: int = 0, **extra: Any) -> dict[str, Any]:
    """One record of the visible conversation."""
    return {
        "type": role,
        "isSidechain": False,
        "userType": "external",
        "timestamp": stamp(at),
        "message": {"role": role, "content": [{"type": "text", "text": text}]},
        **extra,
    }


def worked(at: int) -> dict[str, Any]:
    """A record that moves the Session without putting anything in front of anyone."""
    return {
        "type": "user",
        "isSidechain": False,
        "userType": "external",
        "timestamp": stamp(at),
        "message": {
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": "t1", "content": "ok"}],
        },
    }


def texts(records: list[dict[str, Any]]) -> list[str]:
    entries, _, _ = recent(records, capture=PROGRESS_CAPTURE)
    return [entry.text for entry in entries]


class TestWhatCountsAsProgress:
    """P6's visible half: the conversation, and only the conversation."""

    def test_both_sides_are_carried_and_each_says_which_it_is(self) -> None:
        """Legacy carried the role to the wire; #74's type carries it as a field."""
        entries, omission, _ = recent(
            [said("do the thing", role="user"), said("done", at=1)],
            capture=PROGRESS_CAPTURE,
        )
        assert [(entry.role, entry.text) for entry in entries] == [
            (ProgressRole.USER, "do the thing"),
            (ProgressRole.ASSISTANT, "done"),
        ]
        assert omission is ProgressOmission.NONE

    def test_a_child_process_record_is_not_this_session_speaking(self) -> None:
        """#68's rule, and 32% of real records (`transcript.py:1131-1133`)."""
        assert texts([said("mine"), said("the crew's", at=1, isSidechain=True)]) == ["mine"]

    def test_product_injected_plumbing_is_not_the_user_speaking(self) -> None:
        """A `system` prompt source would be reported back as the user's words."""
        assert texts(
            [said("mine", role="user"), said("injected", role="user", promptSource="system")]
        ) == ["mine"]

    def test_a_slash_command_caveat_is_not_the_user_speaking(self) -> None:
        """Command plumbing rides beside the user's turn (`transcript.py:1515-1562`).

        Its content is a bare string and `isMeta` is set, which is how Claude
        Code 2.1.246 really writes it — read off a live transcript, not assumed.
        """
        caveat = said("mine", role="user")
        caveat["message"]["content"] = (
            "<local-command-caveat>Caveat: The messages below were generated by the user "
            "while running local commands.</local-command-caveat>"
        )
        caveat["isMeta"] = True
        assert texts([caveat, said("mine", role="user", at=1)]) == ["mine"]

    def test_an_unreadable_item_costs_itself_and_nothing_else(self) -> None:
        """Shapes are collected from, never enumerated (`transcript.py:1568-1580`)."""
        mixed = said("kept")
        mixed["message"]["content"] = [
            {"type": "thinking", "thinking": "not for the user"},
            {"type": "text", "text": "kept"},
            {"type": "image", "source": {}},
        ]
        assert texts([mixed]) == ["kept"]

    def test_a_message_with_nothing_readable_is_not_an_entry(self) -> None:
        """`tool_result` and `thinking` never had a say; an empty entry is refused."""
        entries, omission, _ = recent([worked(at=1)], capture=PROGRESS_CAPTURE)
        assert entries == ()
        assert omission is ProgressOmission.NONE

    def test_the_options_of_a_question_are_part_of_what_was_said(self) -> None:
        """#66: without them the user hears the question and never hears the choices."""
        asking = {
            "type": "assistant",
            "isSidechain": False,
            "userType": "external",
            "timestamp": stamp(1),
            "message": {
                "role": "assistant",
                "content": [
                    {
                        "type": "tool_use",
                        "id": "q1",
                        "name": QUESTION_TOOL,
                        "input": {
                            "questions": [
                                {
                                    "question": "Which base?",
                                    "options": [{"label": "main"}, {"label": "feature"}],
                                }
                            ]
                        },
                    }
                ],
            },
        }
        assert texts([asking]) == ["Question: Which base?\nOption: main\nOption: feature"]


class TestTheBound:
    """That this reader is bounded at all, and by the shared rule.

    The rule and its two numbers are `test_progress_bound.py`'s, because both
    lanes share one bound (#76). What is here is that this lane goes through it.
    """

    def test_this_reader_goes_through_it(self) -> None:
        """One wiring check, and the shared module owns the rule itself.

        Both lanes bound their reading with `_progress.bounded`, so asserting the
        drop rule here as well would be one implementation with two sets of tests
        that can disagree about it.
        """
        entries, omission, _ = recent(
            [said("x" * 1_000), said("newest", at=1)],
            capture=capture_for(1_024),
        )

        assert [entry.text for entry in entries] == ["newest"]
        assert omission is ProgressOmission.OLDER


class TestLastActivity:
    """Separate from `progress` on purpose (`seams/agent.py:279-281`)."""

    def test_a_session_that_worked_without_speaking_still_moved(self) -> None:
        """The whole reason the two are different fields."""
        entries, _, moved = recent([said("done", at=0), worked(at=9)], capture=PROGRESS_CAPTURE)
        assert [entry.text for entry in entries] == ["done"]
        assert moved == FIRST.replace(second=9)

    def test_a_child_process_working_is_the_session_working(self) -> None:
        """A sidechain record is not this Session *speaking*; it is it running."""
        _, _, moved = recent(
            [said("mine", at=0), said("the crew's", at=4, isSidechain=True)],
            capture=PROGRESS_CAPTURE,
        )
        assert moved == FIRST.replace(second=4)

    def test_records_with_no_readable_time_are_passed_over(self) -> None:
        """A half-written tail must not blank the time the rest of the file proves."""
        untimed = said("later", at=0)
        untimed["timestamp"] = "not a time"
        _, _, moved = recent([said("earlier", at=3), untimed], capture=PROGRESS_CAPTURE)
        assert moved == FIRST.replace(second=3)

    def test_nothing_read_is_no_time_at_all(self) -> None:
        """`None` is "not read", which no consumer may render as "just now"."""
        assert recent([], capture=PROGRESS_CAPTURE) == ((), ProgressOmission.NONE, None)
