#!/usr/bin/env python3
"""One real Live Call, end to end. Not a test — run it yourself and listen.

Everything in `tests/test_realtime_call.py` runs against a scripted app-server
and a fake audio path, which is what makes it runnable in CI and is also exactly
what it cannot prove: that a real `codex app-server`, a real WebRTC negotiation
and a real pair of audio devices produce a call a person can hear. This script
is that proof, and it exercises the four seam verbs in the order a user would
meet them — bring a call up, say something into it, delegate a turn, hang up.

Run it **from your own terminal**, not from an agent or an IDE. The macOS
microphone grant attaches to the process that asks, so a call started anywhere
else will be silently muted.

    python3 scripts/realtime_call_smoke.py
    python3 scripts/realtime_call_smoke.py --silent   # no audio devices at all
    python3 scripts/realtime_call_smoke.py --delegate "list the files here"

`--silent` opens neither microphone nor speaker: it sends paced silence and
counts the audio frames that come back. That proves the whole signalling route
against a real app-server on a machine with no microphone grant — which is worth
having, but it is *not* the proof this script exists for. Only hearing it is.

Requires the voice extra: `pip install -e '.[voice]'`.
"""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from gpt_voicecoding import __version__  # noqa: E402
from gpt_voicecoding.adapters.call.realtime import RealtimeCallAdapter  # noqa: E402
from gpt_voicecoding.adapters.call.realtime.settings import RealtimeCallSettings  # noqa: E402
from gpt_voicecoding.adapters.call.realtime.webrtc import webrtc_transport  # noqa: E402
from gpt_voicecoding.adapters.codex_app_server.process import OwnedAppServer  # noqa: E402
from gpt_voicecoding.adapters.codex_app_server.settings import CodexSettings  # noqa: E402
from gpt_voicecoding.seams.identity import RequestId  # noqa: E402

#: What the voice thread is told for this run. The real thing is generated by
#: Bridge Core; this is deliberately short, because what is being proved here is
#: the route, not the prose.
INSTRUCTIONS = (
    "You are the voice of the GPT-VoiceCoding bridge, being smoke-tested. "
    "Greet the user in one sentence when the call starts, then answer briefly. "
    "Never invent detail about what the system is doing."
)

#: And what a delegated thread is told, for the same reason.
DELEGATED_INSTRUCTIONS = (
    "You are a delegated turn started by the GPT-VoiceCoding bridge. "
    "Answer in one or two sentences."
)


class Printing:
    """The event sink, printing what the adapter raises upward."""

    def emit(self, event: object) -> None:
        print(f"  event  {type(event).__name__}: {event}", flush=True)


async def main(arguments: argparse.Namespace) -> int:
    logging.basicConfig(level=logging.INFO, format="  log    %(name)s: %(message)s")

    settings = RealtimeCallSettings(workspace=Path(arguments.cwd).expanduser().resolve())
    server = OwnedAppServer(
        settings=CodexSettings(),
        socket_path=Path(arguments.socket),
        log_path=Path(arguments.server_log) if arguments.server_log else None,
        version=__version__,
    )
    adapter = RealtimeCallAdapter(
        sink=Printing(),
        settings=settings,
        transport_factory=lambda: webrtc_transport(
            input_device=arguments.input,
            output_device=arguments.output,
            silent=arguments.silent,
        ),
    )

    print(f"  start  spawning a codex app-server on {arguments.socket}", flush=True)
    await server.start()
    adapter.use_app_server(server)
    await adapter.connect()

    try:
        print("  call   bringing one up (this takes a few seconds)", flush=True)
        snapshot = await adapter.ensure_call(INSTRUCTIONS)
        print(f"  call   {snapshot.state} {snapshot.call_id or ''}", flush=True)
        if not snapshot.is_up:
            print("  call   it never came up; nothing to hear", flush=True)
            return 1

        await asyncio.sleep(arguments.settle)
        receipt = await adapter.speak(arguments.say, request_id=RequestId("smoke-speak"))
        print(f"  speak  {receipt.outcome} {receipt.reason}".rstrip(), flush=True)

        if arguments.delegate:
            print(f"  turn   delegating to {arguments.model}", flush=True)
            reply = await adapter.delegate(
                arguments.delegate,
                model=arguments.model,
                instructions=DELEGATED_INSTRUCTIONS,
                request_id=RequestId("smoke-delegate"),
            )
            print(f"  turn   {reply.model} said: {reply.text}", flush=True)

        print(f"  hold   listening for {arguments.hold:.0f}s — say something", flush=True)
        await asyncio.sleep(arguments.hold)
        return 0
    finally:
        print("  end    hanging up", flush=True)
        with contextlib.suppress(Exception):
            await adapter.end_call()
        await adapter.aclose()
        await server.aclose()
        print("  end    done", flush=True)


def parsed() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--silent", action="store_true", help="open no audio device at all")
    parser.add_argument("--say", default="The bridge is on the line. Can you hear me?")
    parser.add_argument("--delegate", default=None, help="also run one Delegated Turn")
    parser.add_argument(
        "--model",
        default="gpt-5",
        help="the delegated turn's model — the cost lever, so it is stated, never defaulted "
        "by the engine",
    )
    parser.add_argument("--cwd", default=str(Path.home()), help="where the threads run")
    parser.add_argument("--socket", default="/tmp/gpt-voicecoding-smoke/app-server.sock")
    parser.add_argument("--server-log", default=None, help="where the app-server's output goes")
    parser.add_argument("--input", type=int, default=None, help="input device index")
    parser.add_argument("--output", type=int, default=None, help="output device index")
    parser.add_argument("--settle", type=float, default=2.0, help="seconds before speaking")
    parser.add_argument("--hold", type=float, default=30.0, help="seconds to stay on the call")
    return parser.parse_args()


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main(parsed())))
